//! ABI-stable cdylib export for the nfs storage backend.
//!
//! nfs is a **backend-only** plugin, so its entire export is generated by the
//! toolkit's [`export_storage_plugin!`]: the metadata fns, the storage
//! `BackendDef` (derived from [`NfsBackend`]'s own `provider()` — kind, endpoint
//! and capabilities are never restated here), and the proxied-op routing via
//! the shared `plugin_toolkit::storage::dispatch_op`. The per-op `match` and
//! wire-arg structs that used to live here now live once in the storage domain.
//!
//! `abi_stable` remains the crate's one direct non-orca dep because
//! `#[export_root_module]` (which the macro invokes) expands to bare
//! `::abi_stable` paths.

plugin_toolkit::export_storage_plugin! {
    name: "nfs",
    target_compat: "any",
    backend: crate::NfsBackend::new("nfs"),
}
